name: moli_app
description: FLutter doctor appointment - Moli
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  collection: ^1.16.0
  get_it: ^7.2.0
  dio: ^4.0.6
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  formz: ^0.4.1
  hive_flutter: ^1.1.0
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  firebase_analytics: ^9.3.8
  firebase_crashlytics: ^2.9.0
  firebase_dynamic_links: ^4.3.11
  firebase_messaging: ^13.1.0
  firebase_remote_config: ^2.0.20
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  flutter_secure_storage: ^6.0.0
  go_router: ^5.1.0
  connectivity_plus: ^2.3.9
  flutter_ringtone_player: ^3.2.0
  url_launcher: ^6.1.6
  path_provider: ^2.0.11
  package_info_plus: ^2.0.0
  carousel_slider: ^4.1.1
  pinput: ^2.2.16
  moli_shared:
    git:
      url: https://github.com/KLTN-HKI/Moli-Shared.git

dependency_overrides:
  moli_shared:
    path: ../moli_shared

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  freezed: ^2.1.0+1
  hive_generator: ^1.1.3
  json_serializable: ^6.4.1
  intl_utils: ^2.7.0
  build_runner: ^2.2.1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/jsons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
