name: moli_app
description: FLutter doctor appointment - Moli
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  collection: ^1.16.0
  url_launcher: ^6.1.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  auto_route: ^5.0.1
  flutter_screenutil: ^5.5.3+2
  dio: ^4.0.6
  connectivity_plus: ^2.3.5
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.1.4
  introduction_screen: ^3.0.2
  lottie: ^1.4.2
  cached_network_image: ^3.2.2
  formz: ^0.4.1
  path_provider: ^2.0.11
  package_info_plus: ^1.4.3+1
  iconsax: ^0.0.8
  carousel_slider: ^4.1.1

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  auto_route_generator: ^5.0.1
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/jsons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
    - family: MoliIcon
      fonts:
        - asset: assets/icons/MoliIcon.ttf
