name: moli_app
description: FLutter doctor appointment - Moli
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  connectivity_plus: ^2.3.5
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  # Generator
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  generate: true
