/// Flutter icons MoliIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MoliIcon
///      fonts:
///       - asset: fonts/MoliIcon.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class MoliIcon {
  MoliIcon._();

  static const String _kFontFam = 'MoliIcon';

  static const IconData ambulance_fast =
      IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ambulance = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData band_aids = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData bandage = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData blood_bag = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData body = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData bone = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData brain = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData capsule_pill = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData capsule = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData checkup = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData dna = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData drug = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData emergency_light_1 =
      IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData emergency_light_2 =
      IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData erlenmeyer_flask =
      IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData healthcare_call =
      IconData(0xe810, fontFamily: _kFontFam);
  static const IconData heart_rate = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData hospital_symbol =
      IconData(0xe812, fontFamily: _kFontFam);
  static const IconData hexagon_cell = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData hot_meal = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData injection = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData joints_bone = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData location = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData lungs = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData man_with_mask = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData mask = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData medical_kit = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData medical_shield =
      IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData medical_symbol =
      IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData microscope = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData no_smoking = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData nurse = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData oncology = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData overweight = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData pharmacy_symbol =
      IconData(0xe823, fontFamily: _kFontFam);
  static const IconData pill = IconData(0xe824, fontFamily: _kFontFam);
  static const IconData serum = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData shield_virus = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData skull = IconData(0xe827, fontFamily: _kFontFam);
  static const IconData stethoscope_1 = IconData(0xe828, fontFamily: _kFontFam);
  static const IconData test_tube = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData thermometer = IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData toilet_paper = IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData tooth = IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData virus = IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData weight_scale = IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData wheelchair = IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData x_ray_chest = IconData(0xe830, fontFamily: _kFontFam);
  static const IconData x_ray_symbol = IconData(0xe831, fontFamily: _kFontFam);
  static const IconData ambulance_fast_1 =
      IconData(0xe832, fontFamily: _kFontFam);
  static const IconData ambulance_1 = IconData(0xe833, fontFamily: _kFontFam);
  static const IconData band_aids_1 = IconData(0xe834, fontFamily: _kFontFam);
  static const IconData bandage_1 = IconData(0xe835, fontFamily: _kFontFam);
  static const IconData blood_bag_1 = IconData(0xe836, fontFamily: _kFontFam);
  static const IconData body_1 = IconData(0xe837, fontFamily: _kFontFam);
  static const IconData bone_1 = IconData(0xe838, fontFamily: _kFontFam);
  static const IconData brain_1 = IconData(0xe839, fontFamily: _kFontFam);
  static const IconData capsule_1 = IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData checkup_1 = IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData dna_1 = IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData drug_1 = IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData capsule_pill_1 =
      IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData emergency_light_3 =
      IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData emergency_light_4 =
      IconData(0xe840, fontFamily: _kFontFam);
  static const IconData erlenmeyer_flask_1 =
      IconData(0xe841, fontFamily: _kFontFam);
  static const IconData healthcare_call_1 =
      IconData(0xe842, fontFamily: _kFontFam);
  static const IconData heart_rate_1 = IconData(0xe843, fontFamily: _kFontFam);
  static const IconData hexagon_cell_1 =
      IconData(0xe844, fontFamily: _kFontFam);
  static const IconData hospital_symbol_1 =
      IconData(0xe845, fontFamily: _kFontFam);
  static const IconData hot_meal_1 = IconData(0xe846, fontFamily: _kFontFam);
  static const IconData injection_1 = IconData(0xe847, fontFamily: _kFontFam);
  static const IconData joints_bone_1 = IconData(0xe848, fontFamily: _kFontFam);
  static const IconData location_1 = IconData(0xe849, fontFamily: _kFontFam);
  static const IconData lungs_1 = IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData man_with_mask_1 =
      IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData mask_1 = IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData medical_kit_1 = IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData medical_shield_1 =
      IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData medical_symbol_1 =
      IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData microscope_1 = IconData(0xe850, fontFamily: _kFontFam);
  static const IconData no_smoking_1 = IconData(0xe851, fontFamily: _kFontFam);
  static const IconData nurse_1 = IconData(0xe852, fontFamily: _kFontFam);
  static const IconData oncology_1 = IconData(0xe853, fontFamily: _kFontFam);
  static const IconData overweight_1 = IconData(0xe854, fontFamily: _kFontFam);
  static const IconData pharmacy_symbol_1 =
      IconData(0xe855, fontFamily: _kFontFam);
  static const IconData pill_1 = IconData(0xe856, fontFamily: _kFontFam);
  static const IconData serum_1 = IconData(0xe857, fontFamily: _kFontFam);
  static const IconData shield_virus_1 =
      IconData(0xe858, fontFamily: _kFontFam);
  static const IconData skull_1 = IconData(0xe859, fontFamily: _kFontFam);
  static const IconData stethoscope = IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData test_tube_1 = IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData thermometer_1 = IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData toilet_paper_1 =
      IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData tooth_1 = IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData virus_1 = IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData weight_scale_1 =
      IconData(0xe860, fontFamily: _kFontFam);
  static const IconData wheelchair_1 = IconData(0xe861, fontFamily: _kFontFam);
  static const IconData x_ray_chest_1 = IconData(0xe862, fontFamily: _kFontFam);
  static const IconData x_ray_symbol_1 =
      IconData(0xe863, fontFamily: _kFontFam);
}
