// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd9xutCSeEShDg6eWB6p8mXcnHxhGEqN4',
    appId: '1:1061884193636:web:54959d437c82e84b586871',
    messagingSenderId: '1061884193636',
    projectId: 'ancq-developer',
    authDomain: 'ancq-developer.firebaseapp.com',
    storageBucket: 'ancq-developer.appspot.com',
    measurementId: 'G-1CHQDVKH9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtgbmUioXe5-wW3nQZJE6uFBZjN-IvaeA',
    appId: '1:1061884193636:android:25da73a18e11ec3f586871',
    messagingSenderId: '1061884193636',
    projectId: 'ancq-developer',
    storageBucket: 'ancq-developer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlX6r885O9nL9SH-0e9FBou8OChwBTHPk',
    appId: '1:1061884193636:ios:c1bc09b79cbb527f586871',
    messagingSenderId: '1061884193636',
    projectId: 'ancq-developer',
    storageBucket: 'ancq-developer.appspot.com',
    iosClientId: '1061884193636-vsh65mfarhp3o68ungt11o2lkg61gffu.apps.googleusercontent.com',
    iosBundleId: 'com.ancq.moli.dev',
  );
}
